# Generated by Django 6.0.1 on 2026-02-03 17:04

import django.db.models.deletion
import postal_codes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        validators=[postal_codes.utils.validate_postal_code],
                    ),
                ),
                ("block_number", models.CharField(max_length=10)),
                ("road_name", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("x", models.DecimalField(decimal_places=10, max_digits=15)),
                ("y", models.DecimalField(decimal_places=10, max_digits=15)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TrainStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrainStationPostalCodeDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.FloatField()),
                (
                    "postal_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="train_station_postal_code_distance",
                        to="postal_codes.postalcode",
                    ),
                ),
                (
                    "train_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="train_station_postal_code_distance",
                        to="postal_codes.trainstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainStationExit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "train_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="train_station_exits",
                        to="postal_codes.trainstation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("train_station", "latitude", "longitude"),
                        name="unique_train_station_latitude_longitude",
                    )
                ],
            },
        ),
    ]
