# Generated by Django 6.0.1 on 2026-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postal_codes", "0002_seed_train_stations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postalcode",
            name="latitude",
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="longitude",
            field=models.DecimalField(decimal_places=12, max_digits=16),
        ),
    ]
