# Generated by Django 6.0.1 on 2026-01-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("texted", "Texted"),
                            ("soft", "Soft Booking"),
                            ("confirmed", "Confirmed Slot"),
                            ("no_match", "No available matches"),
                        ],
                        default="texted",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=1000),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=8, max_digits=100),
                ),
                (
                    "hours",
                    models.DecimalField(decimal_places=1, default=3, max_digits=10),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="myapp.customer",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="myapp.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
