# Generated by Django 6.0.1 on 2026-01-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="hours",
            field=models.DecimalField(
                choices=[(3, "3"), (3.5, "3.5"), (4, "4"), (4.5, "4.5"), (5, "5")],
                decimal_places=1,
                default=3,
                max_digits=10,
            ),
        ),
    ]
