# Generated by Django 6.0.1 on 2026-01-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_appointment_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-start_time"]},
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="host",
            new_name="coordinator",
        ),
    ]
