# Generated by Django 6.0.1 on 2026-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_customer_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=6, unique=True)),
                ("block_number", models.CharField(max_length=10)),
                ("road_name", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("x", models.DecimalField(decimal_places=10, max_digits=15)),
                ("y", models.DecimalField(decimal_places=10, max_digits=15)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
