# Generated by Django 6.0.1 on 2026-01-30 02:52

import postal_codes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_postalcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postalcode",
            name="id",
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="name",
            field=models.CharField(
                max_length=6,
                primary_key=True,
                serialize=False,
                validators=[postal_codes.utils.validate_postal_code],
            ),
        ),
    ]
