# Generated by Django 6.0.1 on 2026-01-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_postalcode_id_alter_postalcode_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="street_name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="myapp.postalcode"
            ),
        ),
    ]
