# Generated by Django 6.0.1 on 2026-01-30 06:15

import csv
from pathlib import Path
from django.db import migrations
from myapp.models import TrainStation, TrainStationExit

def seed_from_csv(apps, schema_editor):
    csv_path = Path(__file__).parent / 'fixtures' / 'train-stations-coordinates.csv'
    with open(csv_path, 'r') as file:
        reader = csv.DictReader(file, fieldnames=['name','long','lat'])
        for row in reader:
            name = name=row['name']
            name = name.replace('MRT STATION', '')
            name = name.strip().title()
            train_station, created = TrainStation.objects.get_or_create(name=name)
            print(train_station)
            TrainStationExit.objects.create(train_station=train_station, latitude=row['lat'], longitude=row['long'])

def reverse_seed(apps, schema_editor):
    TrainStationExit.objects.all().delete()
    TrainStation.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_trainstation_trainstationexit"),
    ]

    operations = [
         migrations.RunPython(seed_from_csv, reverse_seed),
    ]
