# Generated by Django 6.0.1 on 2026-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_seed_train_stations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainstation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="trainstationexit",
            constraint=models.UniqueConstraint(
                fields=("train_station", "latitude", "longitude"),
                name="unique_train_station_latitude_longitude",
            ),
        ),
    ]
