# Generated by Django 6.0.1 on 2026-01-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_assignedlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainStationPostalCodeDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                (
                    "postal_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.postalcode",
                    ),
                ),
                (
                    "train_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myapp.trainstation",
                    ),
                ),
            ],
        ),
    ]
