# Generated by Django 6.0.1 on 2026-01-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_trainstationpostalcodedistance"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedlocation",
            name="distance_km",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="trainstationexit",
            name="train_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="train_station_exits",
                to="myapp.trainstation",
            ),
        ),
    ]
