# Generated by Django 6.0.1 on 2026-02-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_assignedlocation_distance_km_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainstationpostalcodedistance",
            old_name="distance",
            new_name="distance_km",
        ),
        migrations.AlterField(
            model_name="assignedlocation",
            name="train_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_locations",
                to="myapp.trainstation",
            ),
        ),
        migrations.AlterField(
            model_name="assignedlocation",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_locations",
                to="myapp.worker",
            ),
        ),
        migrations.AlterField(
            model_name="trainstationpostalcodedistance",
            name="postal_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="train_station_postal_code_distance",
                to="myapp.postalcode",
            ),
        ),
        migrations.AlterField(
            model_name="trainstationpostalcodedistance",
            name="train_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="train_station_postal_code_distance",
                to="myapp.trainstation",
            ),
        ),
    ]
