# Generated by Django 6.0.1 on 2026-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0017_rename_distance_trainstationpostalcodedistance_distance_km_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedlocation",
            name="hourly_rate",
            field=models.FloatField(default=20),
        ),
    ]
