# Generated by Django 6.0.1 on 2026-02-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_assignedlocation_hourly_rate"),
        ("postal_codes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainstationpostalcodedistance",
            name="postal_code",
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="postal_codes.postalcode",
            ),
        ),
        migrations.AlterField(
            model_name="assignedlocation",
            name="train_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_locations",
                to="postal_codes.trainstation",
            ),
        ),
        migrations.RemoveField(
            model_name="trainstationpostalcodedistance",
            name="train_station",
        ),
        migrations.RemoveConstraint(
            model_name="trainstationexit",
            name="unique_train_station_latitude_longitude",
        ),
        migrations.DeleteModel(
            name="PostalCode",
        ),
        migrations.DeleteModel(
            name="TrainStationPostalCodeDistance",
        ),
        migrations.RemoveField(
            model_name="trainstationexit",
            name="train_station",
        ),
        migrations.DeleteModel(
            name="TrainStation",
        ),
        migrations.DeleteModel(
            name="TrainStationExit",
        ),
    ]
