# Generated by Django 6.0.1 on 2026-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_remove_trainstationpostalcodedistance_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("confirmed", "Confirmed"),
                    ("done", "Done"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
