# Generated by Django 6.0.1 on 2026-02-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_appointment_paid_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
