# Generated by Django 6.0.1 on 2026-02-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_referrer_remove_customer_coordinator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_address",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
