# Generated by Django 6.0.1 on 2026-02-10 18:09

from django.db import migrations

from myapp.constants import AUTH_GROUP_AFFILIATE

def create_new_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=AUTH_GROUP_AFFILIATE)

def reverse_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=AUTH_GROUP_AFFILIATE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_customer_email_address_alter_customer_phone_number"),
    ]

    operations = [
        migrations.RunPython(create_new_group, reverse_group),
    ]
