# Generated by Django 6.0.1 on 2026-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_seed_group_affiliate_20260211_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="hours",
            field=models.DecimalField(
                choices=[(3, "3"), (3.5, "3.5"), (4, "4")],
                decimal_places=1,
                default=3,
                max_digits=10,
            ),
        ),
    ]
