# Generated by Django 6.0.1 on 2026-02-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_alter_appointment_hours"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Referrer",
            new_name="Affiliate",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="referrer",
            new_name="affiliate",
        ),
    ]
