# Generated by Django 6.0.1 on 2026-02-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_affiliate_code_affiliate_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="myapp.worker",
            ),
        ),
    ]
