# Generated by Django 6.0.1 on 2026-02-11 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_customer_preferred_worker"),
        ("postal_codes", "0003_alter_postalcode_latitude_alter_postalcode_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerWeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "friday_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_schedules_friday",
                        to="postal_codes.trainstation",
                    ),
                ),
                (
                    "monday_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_schedules_monday",
                        to="postal_codes.trainstation",
                    ),
                ),
                (
                    "thursday_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_schedules_thursday",
                        to="postal_codes.trainstation",
                    ),
                ),
                (
                    "tuesday_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_schedules_tuesday",
                        to="postal_codes.trainstation",
                    ),
                ),
                (
                    "wednesday_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekly_schedules_wednesday",
                        to="postal_codes.trainstation",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedule",
                        to="myapp.worker",
                    ),
                ),
            ],
        ),
    ]
