# Generated by Django 6.0.1 on 2026-02-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_workerweeklyschedule"),
        ("postal_codes", "0003_alter_postalcode_latitude_alter_postalcode_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerweeklyschedule",
            name="saturday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_saturday",
                to="postal_codes.trainstation",
                verbose_name="Saturday",
            ),
        ),
        migrations.AddField(
            model_name="workerweeklyschedule",
            name="sunday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_sunday",
                to="postal_codes.trainstation",
                verbose_name="Sunday",
            ),
        ),
        migrations.AlterField(
            model_name="workerweeklyschedule",
            name="friday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_friday",
                to="postal_codes.trainstation",
                verbose_name="Friday",
            ),
        ),
        migrations.AlterField(
            model_name="workerweeklyschedule",
            name="monday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_monday",
                to="postal_codes.trainstation",
                verbose_name="Monday",
            ),
        ),
        migrations.AlterField(
            model_name="workerweeklyschedule",
            name="thursday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_thursday",
                to="postal_codes.trainstation",
                verbose_name="Thursday",
            ),
        ),
        migrations.AlterField(
            model_name="workerweeklyschedule",
            name="tuesday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_tuesday",
                to="postal_codes.trainstation",
                verbose_name="Tuesday",
            ),
        ),
        migrations.AlterField(
            model_name="workerweeklyschedule",
            name="wednesday_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weekly_schedules_wednesday",
                to="postal_codes.trainstation",
                verbose_name="Wednesday",
            ),
        ),
    ]
