# Generated by Django 6.0.1 on 2026-02-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_workerweeklyschedule_saturday_location_and_more"),
        ("postal_codes", "0003_alter_postalcode_latitude_alter_postalcode_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="guest_email_address",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_phone_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_postal_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="postal_codes.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_unit_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="hours",
            field=models.DecimalField(
                choices=[
                    (3, "Suitable for smaller spaces"),
                    (3.5, "Balanced option for medium spaces"),
                    (4, "Recommended for up to 2 bedrooms"),
                ],
                decimal_places=1,
                default=3,
                max_digits=10,
            ),
        ),
    ]
